#!/usr/bin/env bash
# This script is heavily depends on whiptail.
# see: https://en.wikibooks.org/wiki/Bash_Shell_Scripting/Whiptail

max() {
	echo -e "$1\n$2" | sort -n | tail -1
}

getbiggestword() {
	echo "$@" | sed "s/ /\n/g" | wc -L
}

replicate() {
	local n="$1"
	local x="$2"
	local str

	for _ in $(seq 1 "$n"); do
		str="$str$x"
	done
	echo "$str"
}

program_choices() {
	choices=()
	local maxlen
	maxlen="$(getbiggestword "${!checkboxes[@]}")"
	linesize="$(max "$maxlen" 42)"
	local spacer
	spacer="$(replicate "$((linesize - maxlen))" " ")"

	for key in "${!checkboxes[@]}"; do
	    if ! command -v "${checkboxes[$key]}" >/dev/null; then
	    	choices+=("${key}" "${spacer}" "OFF")
		else
		    choices+=("${key}" "${spacer}" "ON")
		fi
	done
}

selected_programs() {
	result=$(
		# Creates the whiptail checklist. Also, we use a nifty
		# trick to swap stdout and stderr.
		whiptail --title "$title" --checklist "$text" 22 "$((linesize + 16))" 12 "${choices[@]}" 3>&2 2>&1 1>&3
	)
}

exit_or_install() {
	local exitstatus="$?"
	if [ "$exitstatus" = 0 ]; then
		# Take the results and remove the "'s and add new lines.
		# Otherwise, pacman is not going to like how we feed it.
		programs=$(echo "$result" | sed 's/" /\n/g' | sed 's/"//g')
		for APP in $programs
		do
       		COUNT=$(dpkg -l | cut -c 1-25 | grep ii | grep -w $APP | wc -l)
       		if test $COUNT = "0"; then
       		    sudo apt install $APP
       		fi
		done
	else
		echo "User selected Cancel."
	fi
}

install() {
	local title="${1}"
	local text="${2}"
	declare -A checkboxes

	# Loop through all the remaining arguments passed to the install function
	for ((i = 3; i <= $#; i += 2)); do
		key="${!i}"
		value=""
		eval "value=\${$((i + 1))}"
		if [ -z "$value" ]; then
			value="$key"
		fi
		checkboxes["$key"]="$value"
	done

	program_choices && selected_programs && exit_or_install
}

install "CLI tools - List 1" " " \
"alacritty" "" "vim-nox" "vim"  "vifm" "" "inxi" "" "htop" "" "nala" "" \
"7zip" "7zz" "rclone" "" "ncdu" "" "mcrypt" "" "nfs-common" "nfsstat"

install "CLI tools - List 2" " " \
"curl" "" "git" "" "zsh" "" "tmux" "" "rsync" "" "unattended-upgrades" "" \
"ydotool" "" "xsel" "" "xdotool" "" "xvkbd" "" "gdebi-core" "gdebi"

install "CLI tools - List 3" " " \
"bat" "batcat" "fzf" "" "meld" ""

install "Multimedia Softwares" " " \
"mplayer" "" "gimp" "" "rhythmbox" "" "vlc" "" "easytag" "" "gcolor3" "" \
"mp3splt-gtk" "" "drawing" "" "openshot-qt" ""

install "Desktop Utilities" " " \
"keepassxc" ""  "gnome-tweaks" "" "numlockx" "" "evince" "" "breaktimer" "" \
"transmission-gtk" "" "virt-manager" "" "thunar" "" \
"thunar-media-tags-plugin" "" "thunar-archive-plugin" "" "thunar-volman" ""

install "Maintenance Tools" " " \
"deja-dup" "" "timeshift" "" "gparted" "" "synaptic" "" "stow" "" "preload" ""



