#!/bin/bash
cp -fp /etc/skel/.nanorc  ~/
cp -fp /etc/skel/.tmux.conf  ~/
cp -fp /etc/skel/.vimrc  ~/
cp -fpr /etc/skel/.vim  ~/
cp -fp /etc/skel/.config/redshift.conf ~/.config/
cp -fpr /etc/skel/.config/alacritty ~/.config/
cp -fpr /etc/skel/.config/btop ~/.config/
cp -fpr /etc/skel/.config/fastfetch ~/.config/
cp -fpr /etc/skel/.config/grsync ~/.config/
cp -fpr /etc/skel/.config/Kvantum ~/.config/
cp -fpr /etc/skel/.config/rofi ~/.config/
cp -fpr /etc/skel/.config/Thunar ~/.config/
cp -fpr /etc/skel/.config/variety ~/.config/
cp -fpr /etc/skel/.config/vifm ~/.config/
cp -fpr /etc/skel/.config/xfce4 ~/.config/
