#!/bin/bash

# ipconfig - Version 2.0 (2025-08-23 - Shavit Ilan)
echo
echo "IP Config - Version 2.0"
echo "======================="
echo
HOSTNAME=$(cat /etc/hostname)
echo "HOSTNAME: $HOSTNAME"
echo
### IP ADDRESS - WIRED ###
CARD=$(ip a | grep ": en\|: et"  |cut -d: -f2 |cut -d" " -f2)
STATUS=$(ip a | grep ": en\|: et" | grep "state UP")
if test $? = "0"; then
    IP=$(/usr/bin/ip -br a |grep en | tr -s ' ' | cut -d" " -f3 | cut -d"/" -f1)
    SUBNET=$(/usr/bin/ip -br a |grep en | tr -s ' ' | cut -d" " -f3 | cut -d"/" -f2)
    echo "WIRED:"
    echo "    STATUS  : UP"
    echo "    NAME    : $CARD"
    echo "    IP      : $IP"
    echo "    SUBNET  : $SUBNET"
else
    echo "WIRED:"
    echo "    STATUS  : DOWN"
    echo "    NAME    : $CARD"
fi

### IP ADDRESS - WIRELESS ###
echo
echo "WIRELESS:"
CARD=$(ip -br a | grep "wl"  |tr -s ' ' |cut -d" " -f1)
STATUS=$(ip -br a | grep "wl" | grep "UP")
if [ $? = "0" ]; then
    IP=$(/usr/bin/ip -br a |grep "wl" | tr -s ' ' | cut -d" " -f3 | cut -d"/" -f1)
    SUBNET=$(/usr/bin/ip -br a |grep "wl" | tr -s ' ' | cut -d" " -f3 | cut -d"/" -f2)
    echo "    STATUS  : UP"
    echo "    NAME    : $CARD"
    echo "    IP      : $IP"
    echo "    SUBNET  : $SUBNET"
else
    echo "    STATUS  : DOWN"
    echo "    NAME    : $CARD"
fi

echo
echo

### DEFAULT GATEWAY ###
DEFAULT=$(ip route show | head -n 1 | cut -d" " -f3)
echo "Default   GW: $DEFAULT"

### DNS ###
TESTCMD=$(resolvectl 2>/dev/null)
if [ $? = "0" ]; then
  DNS=$(resolvectl 2>/dev/null |grep "Current DNS Server" | cut -d' ' -f4 | tr '\n' ' ')
else
  DNS=$(grep nameserver /etc/resolv.conf | head -n 1 | cut -d" " -f2)
fi
echo "DNS   Server: $DNS"

exit 0
