#!/bin/bash

# skel - restore configuration files from /etc/skel

copy_all_skel() {
    echo -n "Are you sure you want to copy ALL files from /etc/skel to your home? Type YES to confirm: "
    read confirm
    if [[ "$confirm" == "YES" ]]; then
        cp -vr /etc/skel/. ~/
    else
        echo "Aborted."
    fi
}

copy_bash_config() {
    cp -v /etc/skel/.bashrc ~/
    cp -v /etc/skel/.bashrc-* ~/
}

copy_fish_config() {
    cp -v /etc/skel/.config/fish/*.fish ~/.config/fish/
}

copy_zsh_config() {
    cp -v /etc/skel/.zshrc ~/
    cp -v /etc/skel/.zshrc-personal ~/
    cp -vr /etc/skel/.oh-my-zsh/ ~/ 2>/dev/null
}

restore_awesome_config() {
    echo -n "Are you sure you want to restore awesome wm config? Type YES to confirm: "
    read confirm
    if [[ "$confirm" == "YES" ]]; then
        cp -vr /etc/skel/.config/awesome/. ~/.config/awesome/ 2>/dev/null
    else
        echo "Aborted."
    fi
}

restore_chadwm_config() {
    echo -n "Are you sure you want to restore chadwm wm config? Type YES to confirm: "
    read confirm
    if [[ "$confirm" == "YES" ]]; then
        cp -vr /etc/skel/.config/arco-chadwm/. ~/.config/arco-chadwm/ 2>/dev/null
    else
        echo "Aborted."
    fi
}

restore_i3_config() {
    echo -n "Are you sure you want to restore i3 config? Type YES to confirm: "
    read confirm
    if [[ "$confirm" == "YES" ]]; then
        cp -vr /etc/skel/.config/i3/. ~/.config/i3/ 2>/dev/null
    else
        echo "Aborted."
    fi
}

restore_qtile_config() {
    echo -n "Are you sure you want to restore qtile config? Type YES to confirm: "
    read confirm
    if [[ "$confirm" == "YES" ]]; then
        cp -vr /etc/skel/.config/qtile/. ~/.config/qtile/ 2>/dev/null
    else
        echo "Aborted."
    fi
}

restore_vim_config() {
    cp -v /etc/skel/.vimrc ~/
    cp -vr /etc/skel/.vim ~/ 2>/dev/null
}

clear
echo "===== skel config restore ====="
echo "1. Copy WHOLE /etc/skel to ~"
echo "2. Restore bash config from /etc/skel"
echo "3. Restore fish config from /etc/skel"
echo "4. Restore zsh config from /etc/skel"
echo "5. Restore awesome wm config from /etc/skel"
echo "6. Restore chadwm wm config from /etc/skel"
echo "7. Restore i3 wm config from /etc/skel"
echo "8. Restore qtile wm config from /etc/skel"
echo "9. Restore vim config from /etc/skel"
echo "==============================="
echo -n "Choose an option [1-9]: "

# Read a single keypress (no Enter)
IFS= read -rsn1 choice
echo

case $choice in
    1) copy_all_skel ;;
    2) copy_bash_config ;;
    3) copy_fish_config ;;
    4) copy_zsh_config ;;
    5) restore_awesome_config ;;
    6) restore_chadwm_config ;;
    7) restore_i3_config ;;
    8) restore_qtile_config ;;
    9) restore_vim_config ;;
    *) echo "Invalid option." ;;
esac

