#!/bin/bash

# skel - restore configuration files from /etc/skel

copy_all_skel() {
    echo -n "Are you sure you want to copy ALL files from /etc/skel to your home? Type YES to confirm: "
    read confirm
    if [[ "$confirm" == "YES" ]]; then
        cp -vr /etc/skel/. ~/
    else
        echo "Aborted."
    fi
}

copy_bash_config() {
    cp -v /etc/skel/.bashrc-* ~/
}

copy_fish_config() {
    cp -v /etc/skel/.config/fish/*.fish ~/.config/fish/
}

copy_zsh_config() {
    cp -v /etc/skel/.zshrc-personal ~/
    rsync -a --delete /etc/skel/.oh-my-zsh/ ~/.oh-my-zsh/
}

restore_suckless_config() {
    echo -n "Are you sure you want to restore suckless config (include chadwm)? Type YES to confirm: "
    read confirm
    if [[ "$confirm" == "YES" ]]; then
        rsync -a --delete /etc/skel/.config/suckless/ ~/.config/suckless/
    else
        echo "Aborted."
    fi
}

restore_vim_config() {
    cp /etc/skel/.vimrc ~/
    rsync -a --delete /etc/skel/.vim/ ~/.vim/
}

clear
echo "===== skel config restore ====="
echo "1. Copy WHOLE /etc/skel to ~"
echo "2. Restore bash config from /etc/skel"
echo "3. Restore fish config from /etc/skel"
echo "4. Restore zsh config from /etc/skel"
echo "5. Restore suckless config (include chadwm) from /etc/skel"
echo "6. Restore vim config from /etc/skel"
echo "==============================="
echo -n "Choose an option [1-6]: "

# Read a single keypress (no Enter)
IFS= read -rsn1 choice
echo

case $choice in
    1) copy_all_skel ;;
    2) copy_bash_config ;;
    3) copy_fish_config ;;
    4) copy_zsh_config ;;
    5) restore_suckless_config ;;
    6) restore_vim_config ;;
    *) echo "Invalid option." ;;
esac

